server:
  port: 8090
spring:
  data:
    mongodb:
      username: kaushald
      password: kaushald
      host: localhost
      port: 27017
      database: customer
      authentication-database: admin